spring.application.name=patient-service

# Database Connection Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clinical_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:clinic_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:clinic_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration (Enterprise Standard)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false